# =============================================================================
# Enrichment Page UI Generation
# =============================================================================
# Static UI scaffolding for the enrichment page. Dynamic run tabs are created
# by ORAEnrichmentSession via func-tabGeneration.R functions.
#
# REMOVED (dead code):
# - generateToolPanel() - replaced by generateToolPanelForRun()
# - generateParametersBox() - replaced by generateParametersBoxForRun()
# - generateResultsPanel() - replaced by generateResultsPanelForRun()
# - generateEnrichmentTab() - replaced by generateEnrichmentTabForRun()
# - generatePlotsPanel() - replaced by generatePlotsPanelForRun()
# - All functions from view-plots.R - replaced by OutputSession classes
# =============================================================================

#' Generate the enrichment page structure
#'
#' Creates the static scaffolding for the enrichment page. The form is generated
#' by enrichmentFormUI() with proper namespacing. Run tabs are inserted dynamically.
#'
#' @param enrichmentType Character, the type of enrichment ("functional")
generateEnrichmentPage <- function(enrichmentType) {
  tags$div(
    tags$h3(paste0(stringr::str_to_title(enrichmentType), " Enrichment Analysis")),
    tags$br(),
    # Form UI is generated by enrichmentFormUI() with proper namespacing
    enrichmentFormUI(ModuleIds$ENRICH_FORM),
    tags$hr(),
    generateEnrichmentResultsPanel()
  )
}

#' Generate the results panel container
#'
#' Creates the container that holds run tabs. Hidden by default, shown when
#' first run is created. Only the Combination tab is static; run tabs are
#' created dynamically by ORAEnrichmentSession.
generateEnrichmentResultsPanel <- function() {
  tags$div(
    id = "functionalEnrichmentResultsPanel",
    class = "toolTabs",
    style = "display: none;",
    tabsetPanel(
      id = "toolTabsPanel",
      # Only Combination tab is static; run tabs are created dynamically
      tabPanel(
        title = "Combination",
        value = "Combination",
        generateCombinationPanel()
      )
    )
  )
}

#' Generate the Combination tab panel
#'
#' Creates the UI for the Combination tab which compares results across
#' multiple enrichment runs. Managed by CombinationSession.
generateCombinationPanel <- function() {
  tags$div(
    tags$br(),
    pickerInput(
      inputId = "combo_datasources",
      label = "Select datasources:",
      choices = NULL,
      selected = NULL,
      multiple = TRUE,
      options = list('actions-box' = TRUE)
    ),
    tags$br(),
    tabsetPanel(
      tabPanel(
        title = "Table",
        icon = icon("table"),
        DT::dataTableOutput("combo_table")
      ),
      tabPanel(
        title = "UpSet Plot",
        icon = icon("chart-column"),
        upsetjs::upsetjsOutput("upsetjsCombo"),
        DT::dataTableOutput("combo_upsetClick_table")
      ),
      tabPanel(
        title = "Combo Network",
        icon = icon("network-wired"),
        fluidRow(
          column(
            4,
            pickerInput(
              inputId = "combo_tool_picker",
              label = "Select edges from tools:",
              choices = c(),
              selected = c(),
              multiple = TRUE,
              width = "80%",
              options = list('actions-box' = TRUE)
            ),
            actionButton(
              inputId = "combo_visNetwork_run",
              label = "Visualize Network",
              icon("paper-plane"),
              class = "submit_button"
            )
          ),
          column(
            4,
            sliderInput(
              inputId = "combo_rank_slider",
              label = "Choose minimum rank threshold:",
              min = 2, max = 4,
              value = 2,
              step = 1,
              width = "70%",
              ticks = FALSE
            ),
            selectInput(
              inputId = "combo_network_layout",
              label = "Choose layout algorithm:",
              choices = as.vector(unlist(LAYOUT_CHOICES))
            )
          )
        ),
        tags$div(
          class = "networkOutput",
          visNetworkOutput("combo_visNetwork", height = "850px")
        ),
        DT::dataTableOutput("combo_network_table")
      )
    )
  )
}
