generateEnrichmentPage <- function(enrichmentType) {
  currentEnrichmentType <<- enrichmentType

  return(
    tags$div(
      tags$h3(paste0(stringr::str_to_title(currentEnrichmentType), " Enrichment Analysis")),
      tags$br(),
      # Form UI is now generated by enrichmentFormUI() with proper namespacing
      enrichmentFormUI(ModuleIds$ENRICH_FORM),
      tags$hr(),
      generateEnrichmentResultsPanel()
    )
  )
}

# generateEnrichmentControlPanel() REMOVED - form UI now in enrichmentFormUI() in enrich-form.R

generateEnrichmentResultsPanel <- function() {
  # Functional enrichment only
  return(
    tags$div(
      id = "functionalEnrichmentResultsPanel",
      class = "toolTabs",
      style = "display: none;",  # Hidden by default, shown when first run is created
      tabsetPanel(
        id = "toolTabsPanel",
        # Only Combination tab is static; run tabs are created dynamically
        tabPanel(
          title = "Combination",
          value = "Combination",
          generateCombinationPanel()
        )
      )
    )
  )
}

# Generate tool panel content
generateToolPanel <- function(toolName) {
  if (toolName != "Combination") {
    currentEnrichmentTool <<- toolName
    currentType_Tool <<- paste(currentEnrichmentType, currentEnrichmentTool, sep = "_")

    return(
      tags$div(
        tags$br(),
        generateParametersBox(),
        tabsetPanel(
          generateResultsPanel(),
          generatePlotsPanel()
        )
      )
    )
  } else {
    generateCombinationPanel()
  }
}

generateParametersBox <- function() {
  box(
    title = "Parameters",
    width = NULL,
    status = "primary",
    solidHeader = T,
    collapsible = T,
    collapsed = T,
    verbatimTextOutput(
      outputId = paste(currentType_Tool, "enrichment_parameters", sep = "_")
    ),
    actionButton(paste(currentType_Tool, "clear", sep = "_"), "Clear", icon("broom"))
  )
}

generateResultsPanel <- function() {
  # Functional enrichment only - all datasource tabs
  sourcesPanel <- do.call(
    tabsetPanel, c(
      id = paste(currentType_Tool, "sources_panel", sep = "_"),
      lapply(TAB_NAMES_CODES, function(tabName) {
        generateEnrichmentTab(tabName)
      })
    )
  )
  
  return(
    tabPanel(
      title = "Results",
      icon = icon("table"),
      tags$div(
        id = paste(currentType_Tool, "resultsDiv", sep = "_"),
        class = "enrichmentResultsDiv",
        tags$br(),
        sourcesPanel
      ),
      tags$br(),
      tags$div(
        id = paste(currentType_Tool, "conversionBoxes", sep = "_"),
        box(
          title = "Conversion Table",
          width = NULL,
          status = "primary",
          solidHeader = TRUE,
          collapsible = TRUE,
          collapsed = TRUE,
          tabsetPanel(
            tabPanel("Input List", DT::dataTableOutput(paste(currentType_Tool, "conversionTable_input", sep = "_"))),
            tabPanel("Reference Background", 
                     div(id=paste(currentType_Tool, "conversionTable_genome_div", sep = "_"),
                         h3("No custom background was submitted by the user, the entire selected genome was used instead.")),
                     div(id=paste(currentType_Tool, "conversionTable_reference_div", sep = "_"), style="display:none",
                       DT::dataTableOutput(paste(currentType_Tool, "conversionTable_reference", sep = "_")))
                     )
            )
        ),
        box(
          title = "Unconverted Inputs",
          class = "conversionBox",
          width = NULL,
          status = "primary",
          solidHeader = TRUE,
          collapsible = TRUE,
          collapsed = TRUE,
          verbatimTextOutput(paste(currentType_Tool, "notConverted_input", sep = "_")),
          tags$hr(),
          div(id=paste(currentType_Tool, "notConverted_reference_div", sep = "_"), style="display:none",
            verbatimTextOutput(paste(currentType_Tool, "notConverted_reference", sep = "_"))
            )
        )
      ),
      box(
        title = "No-hit Inputs",
        class = "conversionBox",
        width = NULL,
        status = "primary",
        solidHeader = TRUE,
        collapsible = TRUE,
        collapsed = TRUE,
        verbatimTextOutput(paste(currentType_Tool, "genesNotFound", sep = "_"))
      )
    )
  )
}

generateEnrichmentTab <- function(tabName) {
  tabPanel(
    title = names(TAB_NAMES[TAB_NAMES == tabName]),
    tags$br(),
    DT::dataTableOutput(paste(currentType_Tool, "table",
                              tabName, sep = "_"))
  )
}

generateCombinationPanel <- function() {
  return(
    tags$div(
      tags$br(),
      pickerInput(
        inputId = "combo_datasources",
        label = "Select datasources:", 
        choices = NULL,
        selected = NULL,
        multiple = T,
        options = list('actions-box' = TRUE)
      ),
      tags$br(),
      tabsetPanel(
        tabPanel(
          title = "Table",
          icon = icon("table"),
          DT::dataTableOutput("combo_table")
        ),
        tabPanel(
          title = "UpSet Plot",
          icon = icon("chart-column"),
          upsetjs::upsetjsOutput("upsetjsCombo"),
          DT::dataTableOutput("combo_upsetClick_table")
        ),
        tabPanel(
          title = "Combo Network",
          icon = icon("network-wired"),
          fluidRow(
            column(
              4,
              pickerInput(
                inputId = "combo_tool_picker",
                label = "Select edges from tools:",
                choices = c(),
                selected = c(),
                multiple = T,
                width = "80%",
                options = list('actions-box' = TRUE)
              ),
              actionButton(
                inputId = "combo_visNetwork_run",
                label = "Visualize Network",
                icon("paper-plane"), class = "submit_button"
              )
            ),
            column(
              4,
              sliderInput(
                inputId = "combo_rank_slider",
                label = "Choose minimum rank threshold:",
                min = 2, max = 4,
                value = 2,
                step = 1,
                width = "70%",
                ticks = F
              ),
              selectInput(
                inputId = "combo_network_layout",
                label = "Choose layout algorithm:",
                choices = as.vector(unlist(LAYOUT_CHOICES))
              )
            )
          ),
          tags$div(
            class = "networkOutput",
            visNetworkOutput("combo_visNetwork", height = VIS_NET_HEIGHT)
          ),
          DT::dataTableOutput("combo_network_table")
        )
      )
    )
  )
}
